// <auto-generated />
using System;
using LghNetCoreLesson12_EF.LghAppDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LghNetCoreLesson12_EF.Migrations
{
    [DbContext(typeof(LghAppDbContext))]
    partial class LghAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LghNetCoreLesson12_EF.Models.LghCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LghCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LghName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("LghStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LghNetCoreLesson12_EF.Models.LghProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LghCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LghCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LghDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<byte[]>("LghImage")
                        .HasColumnType("image");

                    b.Property<string>("LghName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("LghPrice")
                        .HasColumnType("real");

                    b.Property<float>("LghSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("LghStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("LghCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LghNetCoreLesson12_EF.Models.LghProduct", b =>
                {
                    b.HasOne("LghNetCoreLesson12_EF.Models.LghCategory", "LghCategory")
                        .WithMany("LghProducts")
                        .HasForeignKey("LghCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LghCategory");
                });

            modelBuilder.Entity("LghNetCoreLesson12_EF.Models.LghCategory", b =>
                {
                    b.Navigation("LghProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
